GenesysSecurity/GenesysSecurity/urls.py
from django.conf import settings # new
from  django.conf.urls.static import static #new

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('GenesysUserApp.urls')),
    path('main/', include('GenesysAuthenticator.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

GenesysSecurity/GenesysUserApp/urls.py
from django.urls import path
from .views import (
    LoginView,
    LogoutView,
    RegistrationView,
    CustomPasswordChangeView,
    CustomPasswordChangeDoneView,
    DashboardView,
)

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
    path('password-change-done/', CustomPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

GenesysSecurity/GenesysAuthenticator/models.py
from django.db import models
import jsonfield
from GenesysUserApp.models import *
from GenesysUserApp.constants import TABLE_ALIAS_LIST


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class MasterDatabaseSchema(BaseModel):
    database = models.ForeignKey(MasterDatabase, on_delete=models.CASCADE, null=False, blank=False)
    schema = models.CharField(max_length=255, null=False, blank=False)
    is_active = models.BooleanField(null=False, blank=False)

    def __str__(self):
        return self.schema

    class Meta:
        verbose_name = "Database Schema"
        verbose_name_plural = "Database Schemas"


class DatabaseAccess(BaseModel):
    user = models.OneToOneField(UserDetails, on_delete=models.CASCADE, related_name='database_access', null=False,
                                blank=False)
    databases = models.ManyToManyField(MasterDatabase)

    def __str__(self):
        # Assuming MasterDatabase has a 'database_name' field
        databases_str = ', '.join(
            [db.database_name for db in self.databases.all()]) if self.databases.exists() else 'None'
        return f"{self.user.emp_id} - Databases: {databases_str}"


class DatabasePermission(BaseModel):
    user = models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=False, blank=False)
    database = models.ForeignKey(MasterDatabase, on_delete=models.CASCADE, null=False, blank=False)
    granted_by = models.ForeignKey(UserDetails, on_delete=models.SET_NULL, related_name='permissions_given', null=True,
                                   blank=True)
    schema = models.ForeignKey(MasterDatabaseSchema, on_delete=models.CASCADE, null=False, blank=False)
    table_alias = models.CharField(max_length=255, choices=TABLE_ALIAS_LIST, null=False, blank=False)
    db_access = models.BooleanField(default=False)
    privilege_select = models.BooleanField(default=False)
    privilege_insert = models.BooleanField(default=False)
    privilege_update = models.BooleanField(default=False)
    privilege_delete = models.BooleanField(default=False)
    privilege_sequence = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.emp_id}"


class SchemaAccess(BaseModel):
    user = models.ForeignKey(UserDetails, on_delete=models.CASCADE, null=False, blank=False)
    database = models.ForeignKey(MasterDatabase, on_delete=models.CASCADE, null=False, blank=False)
    schema = models.ForeignKey(MasterDatabaseSchema, on_delete=models.CASCADE, null=False, blank=False)
    has_access = models.BooleanField(default=False)


class DatabaseTable(models.Model):
    database = models.ForeignKey(MasterDatabase, on_delete=models.CASCADE, null=False, blank=False)
    schema = models.ForeignKey(MasterDatabaseSchema, on_delete=models.CASCADE, null=False, blank=False)
    table_name = models.CharField(max_length=255, null=False, blank=False)
    columns = jsonfield.JSONField(null=True, blank=True)

    def __str__(self):
        return f"{self.database.database_name} - {self.schema.schema} - {self.table_name}"


class PrivilegeFunctionValidation(BaseModel):
    granted_by = models.ForeignKey(UserDetails, on_delete=models.SET_NULL, related_name='granted_privileges', null=True,
                                   blank=True)
    database = models.ForeignKey(MasterDatabase, on_delete=models.CASCADE, null=False, blank=False)
    schema = models.ForeignKey(MasterDatabaseSchema, on_delete=models.CASCADE, null=False, blank=False)
    table = models.ForeignKey(DatabaseTable, on_delete=models.CASCADE, null=True, blank=True)
    columns = models.CharField(max_length=255, unique=True, null=False, blank=False)
    privilege_function_validation = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.database.database_name} - {self.schema.schema} - {self.table.table_name}"

GenesysSecurity/GenesysAuthenticator/forms.py
from django import forms
from .models import DatabasePermission, MasterDatabase, MasterDatabaseSchema, DatabaseTable, PrivilegeFunctionValidation
from GenesysUserApp.models import *
from GenesysUserApp.constants import TABLE_ALIAS_LIST


class GrantPermissionForm(forms.ModelForm):
    user = forms.ModelChoiceField(queryset=UserDetails.objects.all(), required=True)
    database = forms.ModelChoiceField(queryset=MasterDatabase.objects.all(), required=True)
    schema = forms.ModelChoiceField(queryset=MasterDatabaseSchema.objects.all(), required=False)
    table_alias = forms.ChoiceField(choices=TABLE_ALIAS_LIST, required=True)

    class Meta:
        model = DatabasePermission
        fields = ['user', 'database', 'schema', 'table_alias', 'db_access', 'privilege_select',
                  'privilege_insert', 'privilege_update', 'privilege_delete',
                  'privilege_sequence']

    def __init__(self, *args, **kwargs):
        super(GrantPermissionForm, self).__init__(*args, **kwargs)

        # Customize the choices for the user field
        users = UserDetails.objects.all()
        user_choices = [(user.id, f"{user.email.split('@')[0]} ({user.emp_id})") for user in users]

        # Set the empty label to display a placeholder in the dropdown
        self.fields['user'].choices = [('', 'Select a user')] + user_choices
        self.fields['user'].empty_label = None


class PrivilegeFunctionValidationForm(forms.ModelForm):
    class Meta:
        model = PrivilegeFunctionValidation
        fields = ['database', 'schema', 'table', 'columns', 'privilege_function_validation']

    columns = forms.CharField(max_length=255, required=False, widget=forms.Select(attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Set initial choices for the dropdowns (subject to change dynamically)
        self.fields['database'].queryset = MasterDatabase.objects.filter(is_active=True)
        self.fields['schema'].queryset = MasterDatabaseSchema.objects.filter(is_active=True)
        self.fields['table'].queryset = DatabaseTable.objects.all()
        self.fields['columns'].queryset = []  # Initial empty queryset for columns

        # Add JavaScript event attributes to trigger AJAX requests
        self.fields['database'].widget.attrs['onchange'] = 'load_schemas()'
        self.fields['schema'].widget.attrs['onchange'] = 'load_tables()'
        self.fields['table'].widget.attrs['onchange'] = 'load_columns()'

GenesysSecurity/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>igenesys</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        function load_schemas() {
            var selected_database = $('#id_database').val();
            $.get('/main/get_schemas/', {database_id: selected_database}, function(data) {
                var schemaDropdown = $('#id_schema');
                schemaDropdown.empty();
                schemaDropdown.append('<option value="" selected="selected">---------</option>');
                $.each(data, function(index, item) {
                    schemaDropdown.append($('<option>', {
                        value: item.id,
                        text: item.schema
                    }));
                });
            });
        }

        function load_tables() {
            var selected_schema = $('#id_schema').val();
            $.get('/main/get_tables/', {schema_id: selected_schema}, function(data) {
                var tableDropdown = $('#id_table');
                tableDropdown.empty();
                tableDropdown.append('<option value="" selected="selected">---------</option>');
                $.each(data, function(index, item) {
                    tableDropdown.append($('<option>', {
                        value: item.id,
                        text: item.table_name
                    }));
                });
            });
        }

        function load_columns() {
            var selected_table = $('#id_table').val();
            $.get('/main/get_columns/', {table_id: selected_table}, function(data) {
                var columnDropdown = $('#id_columns');
                columnDropdown.empty();
                columnDropdown.append('<option value="" selected="selected">---------</option>');
                $.each(data.columns, function(index, item) {
                    columnDropdown.append($('<option>', {
                        value: item,
                        text: item
                    }));
                });
            });
        }
    </script>

</head>
<body>
    {% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'dashboard' %}">Navigation Authentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                        aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
<!--                        <li class="nav-item">-->
<!--                            <a class="nav-link" href="">Link</a>-->
<!--                        </li>-->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Permission
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                                <li><a class="dropdown-item" href="{% url 'create_database_permission'%}">Grant_permission</a></li>
                                <li><a class="dropdown-item" href="{% url 'grant_validation'%}">validation</a></li>
                                <li><a class="dropdown-item" href="{% url 'get_data_for_server'%}">Get data from server</a></li
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'change_password' %}">change_password</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="margin-left: 57rem;" href="{% url 'logout' %}" tabindex="-1">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    {% else %}
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'dashboard' %}">Navigation Authentication</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                        aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll1">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" style="margin-left: 70rem;" href="{% url 'logout' %}" tabindex="-1" >Logout</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link"  style="margin-left: 74rem;"  href="{% url 'login' %}" tabindex="-1" >Login</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    {% endif %}
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>